### PR TITLE
Add std.sign and fix division by 0 in stdlib

### LINKED ISSUE #458: Divide by 0 error in std.format
```jsonnet
std.format("%f", [0])
```
```
RUNTIME ERROR: Division by zero.
        std.jsonnet:484:36-44   thunk <n__>
        std.jsonnet:441:25-28   thunk <neg>
        std.jsonnet:445:17-20   function <render_int>
        std.jsonnet:484:25-81   thunk <str>
        std.jsonnet:491:21-24   function <render_float_dec>
        std.jsonnet:(537:21)-(538:76)   function <format_code>
        std.jsonnet:614:29-74   thunk <s>
        std.jsonnet:619:38      thunk <str>
        std.jsonnet:426:36-39   
        std.jsonnet:426:25-40   thunk <w>
        std.jsonnet:422:17      thunk <w>
        std.jsonnet:418:20      function <aux>
        std.jsonnet:422:13-23   function <padding>
        std.jsonnet:426:13-44   function <pad_left>
        std.jsonnet:619:29-53   thunk <s_padded>
        std.jsonnet:625:65-73   thunk <v>
        std.jsonnet:625:21-74   function <format_codes_arr>
        std.jsonnet:625:21-74   function <format_codes_arr>
        std.jsonnet:669:13-52   function <anonymous>
        <stdin>:1:1-24  
```

That seems odd! Same happens for `std.format("%f", 0.0)`

### PR DESCRIPTION
**Pull request by sbarzowski**
Sync with go-jsonnet.
Closes #458

### CODE REVIEW

**Comment by sbarzowski** [comment]
@sparkprime

File: test_suite/run_in_place_tests.sh [hunk 1]
```diff
@@ -0,0 +1,29 @@
+get_abs_filename() {
```
Comment (sparkprime) [inline test_suite/run_in_place_tests.sh]: What's this? :)

Comment (sbarzowski) [reply test_suite/run_in_place_tests.sh]: argh, an accidentally added file
